= Verbi

== Make and let

make and let sono seguiti dal verbo senza to
	
	es: she make me cuddle her


== IF

If I were rich, I'd buy a yatch
nelle situazioni impossibili il tempocambia:

== Da catalogare

presente -> passato: 	We're not having a ...
						If we were having ...
						
passato -> past perfect:	I didn' know ...
							If I had having ...


remember 	to but		: ricordarsi di fare qualcosa
			meeting		: ricordarsi di qualche avvenimento
				
stop 		to talk		: fermarsi per fare qualcosa
			talking		: fermare l'azione
				
try			to make		: senza succcesso 
			making		: prova a fare qualcosa e vedere quello che accade
			
love		to do		: è una cosa giusta da fare
			doing		: mi fa sentire bene
			
Azioni, (non stati) Caratteristichge prevedibili
				si può usare : will -won't per il presente
								would per il passato
								
				He won't talk to anymore until he finish ...
				
Dynamic : azioni 
Statici	: stati	: non hanno -ing


== Tempi

present perfect	: connessione tra il passato ed il presente
continuous		: I have been doing this job
present perfect simple + dynamic: azioni concluse			He has tried to climb Everest 3 times
present perfect simple + static	: azioni ancora in corso	I had my Land Rover for years